import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootProps{
  children: React.ReactNode
}

export default function RootLayout(props: IRootProps) {
  const {children} = props
  
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <Link className="nav-link" href={"/"}>HOME</Link>
            <div>
              <Link className="nav-link" href={"/register"}>REGISTER</Link>
              <Link className="nav-link" href={"/dashboard"}>DASHBOARD</Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer>FOOTER</footer>
      </body>
    </html>
  );
}
